# Generated by Django 4.0.6 on 2022-07-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=208)),
                ('code', models.CharField(blank=True, max_length=280)),
                ('level', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=208)),
                ('code', models.CharField(blank=True, max_length=280)),
                ('level', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
