# Generated by Django 4.0.6 on 2022-07-15 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('level', models.IntegerField(blank=True, default=0)),
                ('good_count', models.IntegerField(blank=True, default=0)),
                ('sub_category_count', models.IntegerField(blank=True, default=0)),
                ('logo', models.ImageField(blank=True, upload_to='upload')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('level', models.IntegerField(blank=True, default=0)),
                ('old_price', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('mini_description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, upload_to='upload')),
                ('logo2', models.ImageField(blank=True, upload_to='upload')),
                ('logo3', models.ImageField(blank=True, upload_to='upload')),
                ('logo4', models.ImageField(blank=True, upload_to='upload')),
                ('logo5', models.ImageField(blank=True, upload_to='upload')),
                ('logo6', models.ImageField(blank=True, upload_to='upload')),
                ('logo_vertical', models.ImageField(blank=True, upload_to='upload')),
                ('logo_horizontal', models.ImageField(blank=True, upload_to='upload')),
                ('description', models.TextField(blank=True)),
                ('weight', models.TextField(blank=True)),
                ('dimensions', models.TextField(blank=True)),
                ('materials', models.TextField(blank=True)),
                ('extra_info', models.TextField(blank=True)),
                ('is_main', models.BooleanField(default=False)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_discount', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.color')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.size')),
            ],
        ),
    ]
