# Generated by Django 4.0.6 on 2022-07-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category_good'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='level',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
