# Generated by Django 4.0.6 on 2022-07-17 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_categorybrand_good_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
        migrations.AddField(
            model_name='good',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='good',
            name='stock',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='size',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
    ]
