# Generated by Django 4.0.6 on 2022-07-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='all_price',
            field=models.FloatField(default=0),
        ),
    ]
