# Generated by Django 4.0.6 on 2022-07-21 02:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_cartitem_all_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 21, 2, 50, 45, 95121)),
        ),
    ]
