# Generated by Django 4.0.6 on 2022-07-27 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_cart_created_at_wishitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 27, 12, 3, 50, 808687)),
        ),
    ]
